package com.amin.pocketgba;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

final class GraphContract {
    static final int CONTRACT_VERSION=2;
    static final String REGISTRY_FORMAT="amin-node-registry",EDGE_FORMAT="amin-typed-edges",APP_ORIGIN="app",HIERARCHY_RELATIONSHIP="contains",HIERARCHY_CLASS="hierarchy",MANIFEST_AUTHORITY="android_manifest";
    static final Set<String> RELATIONSHIP_TYPES=new HashSet<>(Arrays.asList("contains","opens","uses","reads_from","writes_to","executes","depends_on"));
    private GraphContract(){}

    static String capabilityId(String origin,String rawId,String explicit){String e=clean(explicit);if(!e.isEmpty())return e;String o=clean(origin),id=clean(rawId);return o.isEmpty()||id.isEmpty()?"":o+":"+id;}
    static String nodeId(String origin,String rawId){String o=clean(origin),id=clean(rawId);return o.isEmpty()||id.isEmpty()?"":o+":"+id;}
    static boolean isRelationshipTypeAllowed(String type){return RELATIONSHIP_TYPES.contains(clean(type));}

    static String nodeRegistryJson(String raw){JSONObject out=new JSONObject();JSONArray nodes=new JSONArray(),errors=new JSONArray();try{JSONObject graph=new JSONObject(raw==null?"{}":raw);Set<String> caps=new HashSet<>();String rootId=clean(graph.optString("rootId","app-core"));if(rootId.isEmpty())rootId="app-core";JSONObject root=new JSONObject().put("id",rootId).put("title",graph.optString("rootTitle","Amin Pocket")).put("description",graph.optString("rootDescription","")).put("capabilityId",graph.optString("rootCapabilityId","")).put("route",graph.optString("rootRoute","amin-home://open")).put("nodeType","capability").put("status","active").put("nodeVersion","1").put("actions",new JSONArray().put("open")).put("voice",new JSONObject().put("enabled",false).put("aliases",new JSONArray())).put("storage",emptyStorage()).put("filter",new JSONObject()).put("inputContext",new JSONObject());appendUnique(nodes,errors,caps,registryNode(root,""));JSONArray pages=graph.optJSONArray("pages");if(pages!=null)for(int i=0;i<pages.length();i++){JSONObject page=pages.optJSONObject(i);if(page==null)continue;String id=clean(page.optString("id",""));if(id.isEmpty()){errors.put("page["+i+"] missing id");continue;}appendUnique(nodes,errors,caps,registryNode(page,page.optString("parent",rootId)));}out.put("format",REGISTRY_FORMAT).put("version",CONTRACT_VERSION).put("identityRule","capability_id_is_independent_of_name_parent_route_and_position").put("sourceAuthority",MANIFEST_AUTHORITY).put("valid",errors.length()==0).put("errors",errors).put("nodes",nodes);}catch(Exception e){safePut(out,"format",REGISTRY_FORMAT);safePut(out,"version",CONTRACT_VERSION);safePut(out,"valid",false);safePut(out,"errors",new JSONArray().put("invalid app navigation json"));safePut(out,"nodes",nodes);}return out.toString();}

    static String typedEdgesJson(String raw){JSONObject out=new JSONObject();JSONArray edges=new JSONArray();try{JSONObject graph=new JSONObject(raw==null?"{}":raw);String root=clean(graph.optString("rootId","app-core"));if(root.isEmpty())root="app-core";JSONArray pages=graph.optJSONArray("pages");if(pages!=null)for(int i=0;i<pages.length();i++){JSONObject page=pages.optJSONObject(i);if(page==null)continue;String child=clean(page.optString("id",""));if(child.isEmpty())continue;String parent=clean(page.optString("parent",root));if(parent.isEmpty())parent=root;JSONObject e=edge("edge:manifest:"+parent+":"+child,nodeId(APP_ORIGIN,parent),nodeId(APP_ORIGIN,child),HIERARCHY_RELATIONSHIP,"active","1");e.put("relationshipClass",HIERARCHY_CLASS).put("authority",MANIFEST_AUTHORITY).put("structural",true);edges.put(e);}out.put("format",EDGE_FORMAT).put("version",CONTRACT_VERSION).put("hierarchyAuthority",MANIFEST_AUTHORITY).put("relationshipTypes",new JSONArray(RELATIONSHIP_TYPES)).put("edges",edges);}catch(Exception e){safePut(out,"format",EDGE_FORMAT);safePut(out,"version",CONTRACT_VERSION);safePut(out,"edges",edges);}return out.toString();}

    static JSONObject edge(String edgeId,String source,String target,String type,String status,String version)throws JSONException{if(!isRelationshipTypeAllowed(type))throw new JSONException("unsupported relationship type");return new JSONObject().put("edge_id",edgeId).put("edgeId",edgeId).put("source_node_id",source).put("source",source).put("target_node_id",target).put("target",target).put("relationship_type",type).put("relationshipType",type).put("status",clean(status).isEmpty()?"active":status).put("version",clean(version).isEmpty()?"1":version);}

    private static JSONObject registryNode(JSONObject s,String parentRaw)throws JSONException{String rawId=clean(s.optString("id","")),id=nodeId(APP_ORIGIN,rawId),cap=capabilityId(APP_ORIGIN,rawId,s.optString("capabilityId","")),name=s.optString("title",rawId),parent=clean(parentRaw).isEmpty()?"":nodeId(APP_ORIGIN,parentRaw);JSONObject n=new JSONObject();n.put("node_id",id).put("nodeId",id).put("rawId",rawId).put("capability_id",cap).put("capabilityId",cap).put("name",name).put("title",name).put("description",s.optString("description","")).put("node_type",s.optString("nodeType","capability")).put("parent_id",parent).put("parentNodeId",parent).put("status",s.optString("status","active")).put("version",s.optString("nodeVersion","1")).put("actions",copy(s.optJSONArray("actions"))).put("input_contract",s.optString("inputContract","")).put("output_contract",s.optString("outputContract","")).put("route",s.optString("route","")).put("activity",s.optString("activity","")).put("origin",APP_ORIGIN).put("locked",s.optBoolean("locked",true));n.put("voice",s.optJSONObject("voice")==null?new JSONObject().put("enabled",false).put("aliases",new JSONArray()):new JSONObject(s.optJSONObject("voice").toString()));n.put("storage",s.optJSONObject("storage")==null?emptyStorage():new JSONObject(s.optJSONObject("storage").toString()));n.put("filter",s.optJSONObject("filter")==null?new JSONObject():new JSONObject(s.optJSONObject("filter").toString()));n.put("input_context",s.optJSONObject("inputContext")==null?new JSONObject():new JSONObject(s.optJSONObject("inputContext").toString()));return n;}
    private static JSONObject emptyStorage()throws JSONException{return new JSONObject().put("adapter","").put("source_id","").put("table","");}
    private static JSONArray copy(JSONArray a)throws JSONException{return a==null?new JSONArray():new JSONArray(a.toString());}
    private static void appendUnique(JSONArray nodes,JSONArray errors,Set<String> ids,JSONObject n)throws JSONException{String id=n.optString("capability_id","");if(id.isEmpty()){errors.put("node missing capabilityId: "+n.optString("rawId",""));return;}if(!ids.add(id)){errors.put("duplicate capabilityId: "+id);return;}nodes.put(n);}
    private static void safePut(JSONObject o,String k,Object v){try{o.put(k,v);}catch(Exception ignored){}}
    private static String clean(String s){return s==null?"":s.trim();}
}
